# Generated by Django 4.2.7 on 2024-01-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_workoutsexercises_duration_alter_exercises_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='lastPerformed',
            field=models.DateTimeField(null=True),
        ),
    ]
