# Generated by Django 4.2.7 on 2024-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_templateexercises_superset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='exercises',
            field=models.ManyToManyField(to='gym.exercises'),
        ),
    ]
