# Generated by Django 4.2.7 on 2024-01-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_templates_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='cues',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='primary',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='tips',
            field=models.TextField(null=True),
        ),
    ]
