# Generated by Django 4.2.7 on 2024-01-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_exercises_cues_alter_exercises_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateExercises',
        ),
    ]
