# Generated by Django 4.2.7 on 2023-11-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField()),
                ('focus', models.CharField(choices=[('D', 'Duration'), ('R', 'Reps'), ('W', 'Weight')], default='W', max_length=1)),
                ('exercise_type', models.CharField(choices=[('M', 'Machine'), ('D', 'Dumbbell'), ('B', 'Barbell'), ('C', 'Cable'), ('CS', 'Cable Single'), ('B', 'Bodyweight'), ('WB', 'Weighted Bodyweight')], max_length=3)),
                ('description', models.TextField()),
                ('cues', models.TextField()),
                ('tips', models.TextField()),
                ('primary', models.CharField(max_length=35)),
                ('secondary', models.CharField(max_length=35, null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('lastPerformed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('template_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.templates')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.CreateModel(
            name='WorkoutsExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.CharField(max_length=45)),
                ('weights', models.CharField(max_length=60)),
                ('notes', models.TextField()),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercises')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.workouts')),
            ],
        ),
        migrations.AddField(
            model_name='workouts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.user'),
        ),
        migrations.CreateModel(
            name='TemplateExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superset_id', models.IntegerField()),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercises')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.templates')),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('measurement_type', models.TextField(verbose_name=['weight', 'bodyfat', 'muscle mass', 'bicep', 'forearm', 'waist'])),
                ('time', models.DateTimeField()),
                ('unit', models.CharField(choices=[('cm', 'centimeters'), ('in', 'inches'), ('m', 'meters'), ('%', 'percentage'), ('kg', 'kilograms'), ('g', 'grams')], max_length=3)),
                ('value', models.FloatField()),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gym.user')),
            ],
        ),
    ]
